/**
 * CodeGeneratorService — converts design tokens to Tailwind config + React components.
 *
 * Output files:
 *   - tailwind.config.js (extends default theme with project tokens)
 *   - src/design-system/tokens.ts (typed token constants)
 *   - src/design-system/Button.tsx (example generated component)
 */
import { Injectable } from '@nestjs/common';

export interface DesignTokens {
  colors: Record<string, string>;
  typography: Record<string, { fontFamily?: string; fontSize?: string; fontWeight?: string }>;
  spacing: Record<string, string>;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

@Injectable()
export class CodeGeneratorService {
  /**
   * Generates code files from design tokens.
   */
  generate(tokens: DesignTokens, projectName = 'nexusui'): GeneratedFile[] {
    return [
      this.generateTailwindConfig(tokens, projectName),
      this.generateTokenConstants(tokens),
      this.generateButtonComponent(tokens),
    ];
  }

  private generateTailwindConfig(tokens: DesignTokens, projectName: string): GeneratedFile {
    const colors = Object.entries(tokens.colors)
      .map(([key, value]) => `      '${key}': '${value}',`)
      .join('\n');

    const spacing = Object.entries(tokens.spacing)
      .map(([key, value]) => `      '${key}': '${value}',`)
      .join('\n');

    const content = `/** Generated by NexusUI — ${projectName} design system */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
${colors}
      },
      spacing: {
${spacing}
      },
    },
  },
  plugins: [],
};
`;

    return { path: 'tailwind.config.js', content };
  }

  private generateTokenConstants(tokens: DesignTokens): GeneratedFile {
    const colorLines = Object.entries(tokens.colors)
      .map(([key, value]) => `  '${key}': '${value}',`)
      .join('\n');

    const typographyLines = Object.entries(tokens.typography)
      .map(
        ([key, val]) =>
          `  '${key}': { fontFamily: '${val.fontFamily ?? ''}', fontSize: '${val.fontSize ?? ''}', fontWeight: '${val.fontWeight ?? ''}' },`,
      )
      .join('\n');

    const spacingLines = Object.entries(tokens.spacing)
      .map(([key, value]) => `  '${key}': '${value}',`)
      .join('\n');

    const content = `/** Generated by NexusUI — design token constants */
export const colors = {
${colorLines}
} as const;

export const typography = {
${typographyLines}
} as const;

export const spacing = {
${spacingLines}
} as const;
`;

    return { path: 'src/design-system/tokens.ts', content };
  }

  private generateButtonComponent(tokens: DesignTokens): GeneratedFile {
    const primaryColor = Object.keys(tokens.colors)[0] ?? 'blue-500';

    const content = `/** Generated by NexusUI — Button component */
import React from 'react';

interface ButtonProps {
  label: string;
  variant?: 'primary' | 'secondary';
  onClick?: () => void;
  disabled?: boolean;
}

export const Button: React.FC<ButtonProps> = ({
  label,
  variant = 'primary',
  onClick,
  disabled = false,
}) => {
  const base = 'px-4 py-2 rounded font-medium transition-colors';
  const styles =
    variant === 'primary'
      ? \`\${base} bg-[${primaryColor}] text-white hover:opacity-90\`
      : \`\${base} bg-gray-100 text-gray-800 hover:bg-gray-200\`;

  return (
    <button className={styles} onClick={onClick} disabled={disabled}>
      {label}
    </button>
  );
};
`;

    return { path: 'src/design-system/Button.tsx', content };
  }
}
