/**
 * DesignToCodeSyncService — generates code from design tokens and pushes to GitHub.
 *
 * syncMode = 'pr':            create branch → commit → open PR
 * syncMode = 'direct-commit': commit directly to targetBranch
 */
import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../../database/database-service';
import { GitHubAppAuthService } from './github-app-auth.service';
import { GitHubBranchService } from './github-branch.service';
import { CodeGeneratorService } from './code-generator.service';
import type { SyncMode } from './dto/sync-request-dto';
import type { DesignToCodeResult } from './dto/sync-status-dto';
import type { GeneratedFile } from './code-generator.service';

@Injectable()
export class DesignToCodeSyncService {
  private readonly logger = new Logger(DesignToCodeSyncService.name);

  constructor(
    private readonly db: DatabaseService,
    private readonly authService: GitHubAppAuthService,
    private readonly branchService: GitHubBranchService,
    private readonly codeGenerator: CodeGeneratorService,
  ) {}

  async sync(
    projectId: string,
    syncMode: SyncMode,
    targetBranch: string,
  ): Promise<DesignToCodeResult> {
    const connection = await this.db.client.gitHubConnection.findUnique({
      where: { projectId },
    });
    if (!connection) throw new NotFoundException(`No GitHub connection for project ${projectId}`);

    const designSystem = await this.db.client.designSystem.findUnique({
      where: { projectId },
    });
    if (!designSystem) throw new NotFoundException(`No design system for project ${projectId}`);

    // Update status to SYNCING
    await this.db.client.gitHubConnection.update({
      where: { projectId },
      data: { syncStatus: 'SYNCING' },
    });

    try {
      const installationId = Number(connection.installationId);
      const owner = connection.repoOwner;
      const repo = connection.repoName;

      const tokens = {
        colors: designSystem.colorTokens as Record<string, string>,
        typography: designSystem.typographyTokens as Record<string, {
          fontFamily?: string;
          fontSize?: string;
          fontWeight?: string;
        }>,
        spacing: designSystem.spacingTokens as Record<string, string>,
      };

      const files = this.codeGenerator.generate(tokens, repo);
      const result = await this.pushFiles(
        installationId, owner, repo, targetBranch, syncMode, files,
      );

      await this.db.client.gitHubConnection.update({
        where: { projectId },
        data: { syncStatus: 'IDLE', lastSyncAt: new Date() },
      });

      return result;
    } catch (err) {
      await this.db.client.gitHubConnection.update({
        where: { projectId },
        data: { syncStatus: 'ERROR' },
      });
      throw err;
    }
  }

  private async pushFiles(
    installationId: number,
    owner: string,
    repo: string,
    targetBranch: string,
    syncMode: SyncMode,
    files: GeneratedFile[],
  ): Promise<DesignToCodeResult> {
    const octokit = await this.authService.getInstallationOctokit(installationId);
    const baseSha = await this.branchService.getBranchSha(installationId, owner, repo, targetBranch);

    let commitBranch = targetBranch;

    if (syncMode === 'pr') {
      commitBranch = `nexusui/sync-${Date.now()}`;
      await this.branchService.createBranch(installationId, owner, repo, commitBranch, baseSha);
    }

    // Commit each file to the branch
    let lastCommitSha = baseSha;
    for (const file of files) {
      lastCommitSha = await this.commitFile(octokit, owner, repo, commitBranch, file, lastCommitSha);
    }

    if (syncMode === 'pr') {
      const pr = await octokit.rest.pulls.create({
        owner,
        repo,
        title: 'NexusUI: Sync design tokens to code',
        body: `## NexusUI Design Sync\n\nThis PR was automatically generated by NexusUI.\n\n### Changes\n${files.map((f) => `- \`${f.path}\``).join('\n')}`,
        head: commitBranch,
        base: targetBranch,
      });

      this.logger.log(`Created PR #${pr.data.number} for ${owner}/${repo}`);
      return {
        syncMode: 'pr',
        prUrl: pr.data.html_url,
        branch: commitBranch,
        filesChanged: files.length,
      };
    }

    return {
      syncMode: 'direct-commit',
      commitSha: lastCommitSha,
      branch: targetBranch,
      filesChanged: files.length,
    };
  }

  private async commitFile(
    octokit: Awaited<ReturnType<GitHubAppAuthService['getInstallationOctokit']>>,
    owner: string,
    repo: string,
    branch: string,
    file: GeneratedFile,
    _parentSha: string,
  ): Promise<string> {
    // Check if file exists to get its SHA (required for updates)
    let existingSha: string | undefined;
    try {
      const { data } = await octokit.rest.repos.getContent({ owner, repo, path: file.path, ref: branch });
      if (!Array.isArray(data) && data.type === 'file') {
        existingSha = data.sha;
      }
    } catch {
      // File does not exist — create it
    }

    const { data } = await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: file.path,
      message: `chore: update ${file.path} via NexusUI design sync`,
      content: Buffer.from(file.content).toString('base64'),
      branch,
      ...(existingSha ? { sha: existingSha } : {}),
    });

    return (data.commit.sha as string) ?? _parentSha;
  }
}
